# Note: if running the server through docker, use the port defined there instead
@host = http://localhost:3000
# @host = https://gorgonzola-production.up.railway.app

# @name cloudflare_iv_pbc_webhook
POST {{host}}/webhooks
Content-Type: application/json

{
    "value1": "beavers",
    "value2": "ailbe",
    "value3": "3"
}

###

# @name check_root_endpoint
GET {{host}}/
